export const APP_LANG = 'APP_LANG';
export const EDIT_APP_LANG = 'EDIT_APP_LANG';
export const EDIT_COUNTRIES_LIST = 'EDIT_COUNTRIES_LIST';
export const EDIT_SEARCHED_DATA = 'EDIT_SEARCHED_DATA';
export const EDIT_DETAIL_COUNTRY = 'EDIT_DETAIL_COUNTRY';
export const GET_COUNTRY_CODES_LIST = 'GET_COUNTRY_CODES_LIST';
export const COUNTRY_CODES_LIST = 'COUNTRY_CODES_LIST';
export const EDIT_SPINNER_STATE = 'EDIT_SPINNER_STATE';